// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SerialConfig represents the serial port configuration parameters
 */
export class SerialConfig {
    /**
     * Creates a new SerialConfig instance.
     * @param {Partial<SerialConfig>} [$$source = {}] - The source object to create the SerialConfig.
     */
    constructor($$source = {}) {
        if (!("port_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port_name"] = "";
        }
        if (!("baud_rate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["baud_rate"] = 0;
        }
        if (!("data_bits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["data_bits"] = 0;
        }
        if (!("parity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parity"] = "";
        }
        if (!("stop_bits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stop_bits"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SerialConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialConfig(/** @type {Partial<SerialConfig>} */($$parsedSource));
    }
}

/**
 * SerialPortInfo represents a single serial port's basic info
 */
export class SerialPortInfo {
    /**
     * Creates a new SerialPortInfo instance.
     * @param {Partial<SerialPortInfo>} [$$source = {}] - The source object to create the SerialPortInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialPortInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SerialPortInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialPortInfo(/** @type {Partial<SerialPortInfo>} */($$parsedSource));
    }
}

/**
 * SerialStatus represents the current status displayed in the Dashboard status bar
 */
export class SerialStatus {
    /**
     * Creates a new SerialStatus instance.
     * @param {Partial<SerialStatus>} [$$source = {}] - The source object to create the SerialStatus.
     */
    constructor($$source = {}) {
        if (!("is_open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_open"] = false;
        }
        if (!("port_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port_name"] = "";
        }
        if (!("baud_rate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["baud_rate"] = 0;
        }
        if (!("rx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rx_bytes"] = 0;
        }
        if (!("tx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tx_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SerialStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialStatus(/** @type {Partial<SerialStatus>} */($$parsedSource));
    }
}
