// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SerialService handles all serial port operations for the application
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearReceiveBuffer clears the receive data buffer
 * @returns {$CancellablePromise<void>}
 */
export function ClearReceiveBuffer() {
    return $Call.ByID(1495620275);
}

/**
 * CloseSerialPort closes the currently open serial port
 * @returns {$CancellablePromise<void>}
 */
export function CloseSerialPort() {
    return $Call.ByID(3002100442);
}

/**
 * GetSerialPorts lists all available serial ports on the system
 * @returns {$CancellablePromise<$models.SerialPortInfo[]>}
 */
export function GetSerialPorts() {
    return $Call.ByID(3069348807).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetStatus returns the current serial port status for the Dashboard status bar
 * @returns {$CancellablePromise<$models.SerialStatus>}
 */
export function GetStatus() {
    return $Call.ByID(3877356555).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * OpenSerialPort opens the serial port with the specified configuration
 * @param {$models.SerialConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function OpenSerialPort(config) {
    return $Call.ByID(3659862288, config);
}

/**
 * SendData sends data through the serial port
 * format can be: "hex", "ascii", "bin", "dec", "bcd"
 * @param {string} data
 * @param {string} format
 * @returns {$CancellablePromise<number>}
 */
export function SendData(data, format) {
    return $Call.ByID(2753803737, data, format);
}

/**
 * SetAutoSplit configures auto frame splitting parameters
 * splitMs: the idle time in milliseconds to consider a frame complete
 * @param {boolean} enabled
 * @param {number} ms
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoSplit(enabled, ms) {
    return $Call.ByID(146652590, enabled, ms);
}

/**
 * StartAutoSend starts periodic auto-send with the given data, format, and interval (in seconds)
 * @param {string} data
 * @param {string} format
 * @param {number} intervalSec
 * @returns {$CancellablePromise<void>}
 */
export function StartAutoSend(data, format, intervalSec) {
    return $Call.ByID(3622907244, data, format, intervalSec);
}

/**
 * StopAutoSend stops the periodic auto-send
 * @returns {$CancellablePromise<void>}
 */
export function StopAutoSend() {
    return $Call.ByID(705049162);
}

// Private type creation functions
const $$createType0 = $models.SerialPortInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SerialStatus.createFrom;
